### ISSUE TITLE
Cannot find module '@babel/core/package.json' in node12.x and node 14.x

### ISSUE THREAD

**Issue by Aisen60** [AlloyTeam/eslint-config-alloy#208]
按照文档上的[配置说明](https://github.com/AlloyTeam/eslint-config-alloy#built-in)进行了配置，发现当 node 版本为12.22.5和14.17.5 时，提示：

```
Error: Failed to load parser '@babel/eslint-parser' declared in '.eslintrc.js » eslint-config-alloy » ./base.js': Cannot find module '@babel/core/package.json'
```

<img alt="eslint-node-v12.22.5 " src="https://user-images.githubusercontent.com/19791710/143776388-74a45abf-978c-49ce-ada5-b506de847086.png">

<img  alt="eslint-node-v14.17.5" src="https://user-images.githubusercontent.com/19791710/143776380-ab0aeab5-1f9c-44ef-bda7-11d53cce8908.png">

详细错误：

```
Failed to load parser '@babel/eslint-parser' declared in '.eslintrc.js » eslint-config-alloy » ./base.js': Cannot find module '@babel/core/package.json'
Require stack:
- /Users/aisen60/Desktop/eslint-node-v14.17.5/node_modules/@babel/eslint-parser/lib/parse.cjs
- /Users/aisen60/Desktop/eslint-node-v14.17.5/node_modules/@babel/eslint-parser/lib/index.cjs
- /Users/aisen60/Desktop/eslint-node-v14.17.5/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at Object.<anonymous> (/Users/aisen60/Desktop/eslint-node-v14.17.5/node_modules/@babel/eslint-parser/lib/parse.cjs:17:19)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

配置如下（`package.json`）：

- node@12.22.5
```json
{
  "name": "eslint-node-v12.22.5",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/eslint-parser": "^7.15.8",
    "eslint": "^7.32.0",
    "eslint-config-alloy": "^4.4.0"
  }
}

```

- node@14.17.5
```json
{
  "name": "eslint-node-v14.17.5",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/eslint-parser": "^7.15.8",
    "eslint": "^7.32.0",
    "eslint-config-alloy": "^4.4.0"
  }
}

```

而当 node 版本为 16.13.0 时，无异常（配置同上）。

<img alt="eslint-node-v16.13.0" src="https://user-images.githubusercontent.com/19791710/143776444-bacf0020-62ba-4ffd-86c4-f442012d6e4d.png">

**Comment by Renderz** [comment]
node 16.13.2有同样的问题，安装@babel/core就OK了。
