### ISSUE TITLE
在 vue-cli 默认的webpack 模板工程中使用出错

### ISSUE THREAD

**Issue by Hellowor1d** [AlloyTeam/eslint-config-alloy#35]
### 首先感谢这么详尽友好的配置，然后想要反馈下问题:

这套配置，直接在 vue init  webpack 的模板工程里会报错

### 复现过程如下：

1.  vue init webpack vue-webpack-tpl，eslint 默认 风格 standard
2.  以上可正常运行，之后，安装eslint-config-alloy   vue 配置相关
```
npm install --save-dev eslint babel-eslint vue-eslint-parser@2.0.1-beta.2 eslint-plugin-vue@3 eslint-config-alloy
```
3.  替换.eslintrc.js 中  extends:'eslint-config-alloy/vue'
4.  npm start 之后出错：
```js
 ERROR  Failed to compile with 1 errors                                                                                       14:12:49

 error  in ./src/main.js

Module build failed: Error: /Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint-config-alloy/index.js:
        Configuration for rule "no-multi-spaces" is invalid:
        Value "data["0"].ignoreEOLComments" has additional properties.

Referenced from: eslint-config-alloy/vue
Referenced from: /Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/.eslintrc.js
    at validateRuleOptions (/Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint/lib/config/config-validator.js:109
:15)
    at Object.keys.forEach.id (/Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint/lib/config/config-validator.js:
156:13)
    at Array.forEach (<anonymous>)
    at Object.validate (/Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint/lib/config/config-validator.js:155:35)
    at load (/Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint/lib/config/config-file.js:559:19)
    at configExtends.reduceRight (/Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint/lib/config/config-file.js:42
4:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint/lib/config/config-file.js:408:28)
    at load (/Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint/lib/config/config-file.js:566:22)
    at configExtends.reduceRight (/Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (/Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint/lib/config/config-file.js:566:22)
    at loadConfig (/Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/liuml/Workspace/personal/Vue/vue-webpack-tpl/node_modules/eslint/lib/config.js:260:26)

 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.js
```

**Comment by xcatliu** [comment]
看上去是 eslint 版本较低，导致无法识别 no-multi-spaces 的配置。可以尝试删除 node_modules 目录，然后执行
```sh
npm install --save-dev eslint babel-eslint vue-eslint-parser@2.0.1-beta.2 eslint-plugin-vue@3 eslint-config-alloy

**Comment by Hellowor1d** [comment]
@xcatliu 
谢谢
但是我按照你上述的方法进行操作，报错依然存在。
以我最初的问题为基础，
继续尝试如下操作：
1.  手动 修改 package.json 中 eslint  到 4.13.1 ,重新删除 node_modules ,然后 npm install , npm start
错误依然存在，但是报错好像有变化（抱歉这部分报错没保留）；
2.  看到报错有变怀疑确实可能跟 eslint 版本有关，然后索性把 所有 eslint 相关插件版本号都指定到“latest ”,重新删除 node_modules ,然后 npm install , npm start，再来过。
出现如下错误：
```


  ✘  https://google.com/#q=vue%2Fvalid-v-show                     Definition for rule 'vue/valid-v-show' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fvalid-v-text                     Definition for rule 'vue/valid-v-text' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Frequire-render-return            Definition for rule 'vue/require-render-return' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Freturn-in-computed-property      Definition for rule 'vue/return-in-computed-property' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fvalid-template-root              Definition for rule 'vue/valid-template-root' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fvalid-v-bind                     Definition for rule 'vue/valid-v-bind' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fvalid-v-cloak                    Definition for rule 'vue/valid-v-cloak' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fvalid-v-else-if                  Definition for rule 'vue/valid-v-else-if' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fvalid-v-else                     Definition for rule 'vue/valid-v-else' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fvalid-v-for                      Definition for rule 'vue/valid-v-for' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fvalid-v-html                     Definition for rule 'vue/valid-v-html' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fvalid-v-if                       Definition for rule 'vue/valid-v-if' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fvalid-v-model                    Definition for rule 'vue/valid-v-model' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fvalid-v-on                       Definition for rule 'vue/valid-v-on' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fvalid-v-once                     Definition for rule 'vue/valid-v-once' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fvalid-v-pre                      Definition for rule 'vue/valid-v-pre' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fno-parsing-error                 Definition for rule 'vue/no-parsing-error' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fno-reservered-keys               Definition for rule 'vue/no-reservered-keys' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fno-async-in-computed-properties  Definition for rule 'vue/no-async-in-computed-properties' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fno-confusing-v-for-v-if          Definition for rule 'vue/no-confusing-v-for-v-if' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fno-duplicate-attributes          Definition for rule 'vue/no-duplicate-attributes' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fno-textarea-mustache             Definition for rule 'vue/no-textarea-mustache' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Forder-in-components              Definition for rule 'vue/order-in-components' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Frequire-component-is             Definition for rule 'vue/require-component-is' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Frequire-v-for-key                Definition for rule 'vue/require-v-for-key' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fhtml-quotes                      Definition for rule 'vue/html-quotes' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=vue%2Fno-multi-spaces                  Definition for rule 'vue/no-multi-spaces' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=import%2Fextensions                    Definition for rule 'import/extensions' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  https://google.com/#q=import%2Fno-extraneous-dependencies    Definition for rule 'import/no-extraneous-dependencies' was not found
  src/main.js:1:1
  // The Vue build version to load with the `import` command
   ^

  ✘  http://eslint.org/docs/rules/indent                          Expected indentation of 4 spaces but found 2
  src/main.js:11:1
    el: '#app',
   ^

  ✘  http://eslint.org/docs/rules/indent                          Expected indentation of 4 spaces but found 2
  src/main.js:12:1
    router,
   ^

  ✘  http://eslint.org/docs/rules/indent                          Expected indentation of 4 spaces but found 2
  src/main.js:13:1
    template: '<App/>',
   ^

  ✘  http://eslint.org/docs/rules/indent                          Expected indentation of 4 spaces but found 2
  src/main.js:14:1
    components: { App }
   ^


✘ 33 problems (33 errors, 0 warnings)


Errors:
  4  http://eslint.org/docs/rules/indent
  1  https://google.com/#q=vue%2Fvalid-v-pre
  1  https://google.com/#q=vue%2Fno-parsing-error
  1  https://google.com/#q=vue%2Fvalid-v-show
  1  https://google.com/#q=vue%2Fno-reservered-keys
  1  https://google.com/#q=vue%2Frequire-render-return
  1  https://google.com/#q=vue%2Fno-async-in-computed-properties
  1  https://google.com/#q=vue%2Fvalid-template-root
  1  https://google.com/#q=vue%2Fno-confusing-v-for-v-if
  1  https://google.com/#q=vue%2Fvalid-v-cloak
  1  https://google.com/#q=vue%2Fno-duplicate-attributes
  1  https://google.com/#q=vue%2Fvalid-v-else
  1  https://google.com/#q=vue%2Fno-textarea-mustache
  1  https://google.com/#q=vue%2Fvalid-v-html
  1  https://google.com/#q=vue%2Forder-in-components
  1  https://google.com/#q=vue%2Fvalid-v-model
  1  https://google.com/#q=vue%2Frequire-component-is
  1  https://google.com/#q=vue%2Fvalid-v-once
  1  https://google.com/#q=vue%2Frequire-v-for-key
  1  https://google.com/#q=vue%2Freturn-in-computed-property
  1  https://google.com/#q=vue%2Fvalid-v-else-if
  1  https://google.com/#q=import%2Fno-extraneous-dependencies
  1  https://google.com/#q=import%2Fextensions
  1  https://google.com/#q=vue%2Fno-multi-spaces
  1  https://google.com/#q=vue%2Fhtml-quotes
  1  https://google.com/#q=vue%2Fvalid-v-for
  1  https://google.com/#q=vue%2Fvalid-v-bind
  1  https://google.com/#q=vue%2Fvalid-v-text
  1  https://google.com/#q=vue%2Fvalid-v-on
  1  https://google.com/#q=vue%2Fvalid-v-if
```

**Comment by xcatliu** [comment]
全部 @latest 是不行的，这两个必须用指定的版本
```
vue-eslint-parser@2.0.1-beta.2 eslint-plugin-vue@3
```
