### ISSUE TITLE
code ELIFECYCLE

### ISSUE THREAD

**Issue by yuwanlin** [AlloyTeam/eslint-config-alloy#45]
hello, there is a error, but I am not sure where it from.
```
 yu$ npm run lint

> projectName
> eslint --ext .js --ext .jsx fileloader

eslint-config-alloy/react:
        Configuration for rule "react/jsx-curly-spacing" is invalid:
        Value "[object Object]" must be an enum value.

Referenced from: path/.eslintrc.js
Error: eslint-config-alloy/react:
        Configuration for rule "react/jsx-curly-spacing" is invalid:
        Value "[object Object]" must be an enum value.

Referenced from: path/.eslintrc.js
    at validateRuleOptions (path/node_modules/eslint/lib/config/config-validator.js:109:15)
    at Object.keys.forEach.id (path/node_modules/eslint/lib/config/config-validator.js:156:13)
    at Array.forEach (<anonymous>)
    at Object.validate (path/node_modules/eslint/lib/config/config-validator.js:155:35)
    at load (path/node_modules/eslint/lib/config/config-file.js:559:19)
    at configExtends.reduceRight (path/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (path/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (path/node_modules/eslint/lib/config/config-file.js:566:22)
    at loadConfig (path/node_modules/eslint/lib/config.js:63:33)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! projectName@ lint: `eslint --ext .js --ext .jsx folderName
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the projectName lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yu/.npm/_logs/2018-08-16T01_21_35_977Z-debug.log
```

when I do steps:
```
npm cache clean --force
delete node_modules
npm i
```
or comment 'react/jsx-curly-spacing' rule like this(eslint-config-alloy/react.js)
```
        // @fixable 大括号内前后禁止有空格
        // 'react/jsx-curly-spacing': [
        //     'error',
        //     {
        //         when: 'never',
        //         attributes: {
        //             allowMultiline: true
        //         },
        //         children: true,
        //         spacing: {
        //             objectLiterals: 'never'
        //         }
        //     }
        // ],
```

the problem is still exist.

## .eslintrc.js
```
module.exports = {
  extends: [
    "eslint-config-alloy/react"
  ],
  "parserOptions": {
    "ecmaFeatures": {
      "arrowFunctions": true,
      "binaryLiterals": true,
      "blockBindings": true,
      "classes": true,
      "defaultParams": true,
      "destructuring": true,
      "forOf": true,
      "generators": true,
      "modules": true,
      "objectLiteralComputedProperties": true,
      "objectLiteralDuplicateProperties": true,
      "objectLiteralShorthandMethods": true,
      "objectLiteralShorthandProperties": true,
      "octalLiterals": true,
      "regexUFlag": true,
      "regexYFlag": true,
      "spread": true,
      "superInFunctions": true,
      "templateStrings": true,
      "unicodeCodePointEscapes": true,
      "globalReturn": true,
      "jsx": true
    }
  },

  "env": {
    "browser": true,
    "node": true,
    "es6": true,
    "jquery": true
  },

  "parser": "babel-eslint",

  "plugins": ["react"],

  "rules": {
    // some rules
  },
  
  "globals": {
    
  }
}

```

and the version:
```
node: 8.11.3
npm: 5.6.0
eslint: 3.19.0
babel-eslint: 7.0.0
eslint-loader: 2.0.0
babel-plugin-react: 6.10.3
eslint-config-alloy: 1.4.2
```

**Comment by xcatliu** [comment]
Please try the latest version of `eslint`, `babel-eslint` and `babel-plugin-react`

**Comment by xcatliu** [comment]
Is this problem still exist in the latest version of eslint-config-alloy?
