### ISSUE TITLE
为啥用Typescript还要依赖babel-eslint

### ISSUE THREAD

**Issue by ldc4** [AlloyTeam/eslint-config-alloy#55]
[!] (eslint plugin) Error: Cannot find module 'babel-eslint'
Referenced from: /Users/xxx/Desktop/xx/node_modules/eslint-config-alloy/index.js
Referenced from: /Users/xxx/Desktop/xx/node_modules/eslint-config-alloy/typescript.js
Referenced from: /Users/xxx/Desktop/xx/.eslintrc
src/index.ts
Error: Cannot find module 'babel-eslint'
Referenced from: /Users/xxx/Desktop/xx/node_modules/eslint-config-alloy/index.js
Referenced from: /Users/xxx/Desktop/xx/node_modules/eslint-config-alloy/typescript.js
Referenced from: /Users/xxx/Desktop/xx/.eslintrc
    at ModuleResolver.resolve (/Users/xxx/Desktop/xx/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at loadFromDisk (/Users/xxx/Desktop/xx/node_modules/eslint/lib/config/config-file.js:537:42)
    at load (/Users/xxx/Desktop/xx/node_modules/eslint/lib/config/config-file.js:587:20)
    at configExtends.reduceRight (/Users/xxx/Desktop/xx/node_modules/eslint/lib/config/config-file.js:453:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/xxx/Desktop/xx/node_modules/eslint/lib/config/config-file.js:431:26)
    at loadFromDisk (/Users/xxx/Desktop/xx/node_modules/eslint/lib/config/config-file.js:551:22)
    at load (/Users/xxx/Desktop/xx/node_modules/eslint/lib/config/config-file.js:587:20)
    at configExtends.reduceRight (/Users/xxx/Desktop/xx/node_modules/eslint/lib/config/config-file.js:453:36)
    at Array.reduceRight (<anonymous>)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xx@0.0.1 build: `rollup -c config/rollup.config.js`
npm ERR! Exit status 1

**Comment by xcatliu** [comment]
是一个 eslint 已知问题 https://github.com/eslint/eslint/issues/11396 https://github.com/eslint/eslint/issues/11240
但是 eslint 官方似乎并不打算修复它。

我们可以在 eslint-config-alloy 中不使用 extends 而是直接 merge 好之后再生成 eslint 配置便可修复

**Comment by ldc4** [comment]
好吧，不过我用原生的plugin:@typescript-eslint/recommended
似乎没有这个问题了。

module.exports =  {
  parser:  '@typescript-eslint/parser',       // ESLint支持typescript的解析器
  extends:  [
    'plugin:@typescript-eslint/recommended',  // 使用@typescript-eslint/eslint-plugin推荐的规则
    'prettier/@typescript-eslint',            // 避免prettier与@typescript-eslint/eslint-plugin的规则冲突
    'plugin:prettier/recommended',            // 使用eslint-plugin-prettier的规则，显示prettier错误为eslint错误，确保放在最后
  ],
  parserOptions:  {
    // ecmaVersion:  2018,                       // 允许解析现代ECMAScript特性
    sourceType:  'module',                    // 允许使用导入
  },
  rules:  {
    // 自定义规则，用于覆盖extends引入的规则
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/explicit-function-return-type": "off"
  },
};

**Comment by ldc4** [comment]
好的，了解

**Comment by xcatliu** [comment]
这个 bug 看上去已经被解决了，可以不用安装 babel-eslint 了
