### ISSUE TITLE
TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by yanglinxiao** [AlloyTeam/eslint-config-alloy#81]
1、我在vue-cli3的selint配置文件配置eslint-config-alloy/vue，运行eslint检测 npm run lint 都会报错，我去掉eslint-config-alloy/vue，采取vue默认的检测完全没问题；
2、尝试更换babel-eslint版本均无效。

**### eslint配置文件如下：**
```
module.exports = {
  root: true,
  env: {
    'node': true
  },
  extends: [
    'eslint-config-alloy/vue'
  ],
  rules: {
    'no-unused-vars': [1, {
      // 允许声明未使用变量
      'vars': 'local',
      // 参数不检查
      'args': 'none'
    }],
    'no-new': 1,
    'no-console': 0,
    'indent': 0,
    'camelcase': 0,
    'semi': [1, 'always'],
    'object-curly-spacing': [1, 'always'],
    'quotes': [1, 'single']
  },
  parserOptions: {
    'parser': 'babel-eslint'
  }
}
```

**### package.json有关babel和eslint信息：**
```
    "babel-eslint": "^10.0.1",
    "babel-plugin-component": "^1.1.1",
    "eslint": "^5.16.0",
    "eslint-config-alloy": "^2.0.4",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-vue": "^5.2.2",
    "vue-eslint-parser": "^5.0.0"
```

**### 报错信息如下：**
```
TypeError: Cannot read property 'type' of null
Occurred while linting /Users/yanglinxiao/Workspace/web/src/pages/main/pages/appSolution/detail/index.vue:137
    at validateBraceSpacing (/Users/yanglinxiao/Workspace/web/node_modules/eslint/lib/rules/object-curly-spacing.js:180:119)
    at EventEmitter.checkForObject (/Users/yanglinxiao/Workspace/web/node_modules/eslint/lib/rules/object-curly-spacing.js:231:13)
    at EventEmitter.emit (events.js:188:13)
    at NodeEventGenerator.applySelector (/Users/yanglinxiao/Workspace/web/node_modules/vue-eslint-parser/index.js:3128:26)
    at NodeEventGenerator.applySelectors (/Users/yanglinxiao/Workspace/web/node_modules/vue-eslint-parser/index.js:3142:22)
    at NodeEventGenerator.enterNode (/Users/yanglinxiao/Workspace/web/node_modules/vue-eslint-parser/index.js:3150:14)
```

**Comment by xcatliu** [comment]
应该和 vue-eslint-parser 版本有关，试试最新的？https://github.com/AlloyTeam/eslint-config-alloy#vue
